Select 
SISTEMA_BMS_ORDENES.VEHICULO,
SISTEMA_BMS_ORDENES.SOC,


--COUNT(DISTINCT(VEHICULO)) BOTS,
--COUNT(1) Operaciones,
SISTEMA_BMS_ORDENES.FECHA,
ORDENES_AUX.FECHA FECHA_SIG_OPER,
ORDENES_AUX.VEHICULO VEHICULO,
-- Queremos saber si la operación es la última del Bot antes de ir a cargar
Case
	When Exists 
	(Select * 
	FROM SISTEMA_BMS_BIBERON_ENTRAR 
	WHERE 
	SISTEMA_BMS_ORDENES.VEHICULO = SISTEMA_BMS_BIBERON_ENTRAR.VEHICULO
	AND SISTEMA_BMS_BIBERON_ENTRAR.FECHA > SISTEMA_BMS_ORDENES.FECHA
	AND SISTEMA_BMS_BIBERON_ENTRAR.FECHA < ORDENES_AUX.FECHA)
	tHEN 1
	Else 0
End MCA_CARGAR,
-- Queremos saber el número de operaciones registradas en la última hora
(Select count (*) 
from SISTEMA_BMS_ORDENES aux2 
where 
aux2.fecha  < = SISTEMA_BMS_ORDENES.FECHA
and aux2.fecha > DATEADD ( hour, -1 , SISTEMA_BMS_ORDENES.FECHA )
) Carga_Trabajo,
-- Queremos saber el número de bots activos en la última hora
(Select count (distinct(VEHICULO)) 
from SISTEMA_BMS_ORDENES aux2 
where 
aux2.fecha  < = SISTEMA_BMS_ORDENES.FECHA
and aux2.fecha > DATEADD ( hour, -1 , SISTEMA_BMS_ORDENES.FECHA )
) Bots_Activos,
convert(date, SISTEMA_BMS_ORDENES.FECHA, 103) fecha,

MONTH(SISTEMA_BMS_ORDENES.FECHA) Mes,
DATEPART(dw, SISTEMA_BMS_ORDENES.FECHA) dia_semana,
CONVERT(VARCHAR(2), SISTEMA_BMS_ORDENES.FECHA, 108) hora
from SISTEMA_BMS_ORDENES
-- Buscamos siguiente movimiento del bot
left join
	SISTEMA_BMS_ORDENES ORDENES_AUX
On SISTEMA_BMS_ORDENES.VEHICULO = ORDENES_AUX.VEHICULO
And ORDENES_AUX.FECHA = (Select min(FECHA) 
						FROM SISTEMA_BMS_ORDENES ORDENES_AUX2 
						WHERE 
						ORDENES_AUX2.VEHICULO = SISTEMA_BMS_ORDENES.VEHICULO
						And ORDENES_AUX2.FECHA > SISTEMA_BMS_ORDENES.FECHA)
WHERE SISTEMA_BMS_ORDENES.FECHA >='2017/01/10'
