Select
SISTEMA_BMS_BIBERON_ENTRAR.VEHICULO,
SISTEMA_BMS_BIBERON_ENTRAR.FECHA FECHA_ENTRADA,
SISTEMA_BMS_BIBERON_SALIR.FECHA FECHA_SALIDA,
DATEDIFF ( MINUTE , SISTEMA_BMS_BIBERON_SALIR.FECHA , SISTEMA_BMS_BIBERON_ENTRAR.FECHA) dif_minutos,
(SISTEMA_BMS_BIBERON_ENTRAR.T1_DISTANCIA + SISTEMA_BMS_BIBERON_ENTRAR.T2_DISTANCIA + SISTEMA_BMS_BIBERON_ENTRAR.T3_DISTANCIA + SISTEMA_BMS_BIBERON_ENTRAR.T4_DISTANCIA) DISTANCIA_TOTAL,
(SISTEMA_BMS_BIBERON_ENTRAR.T1_consumo + SISTEMA_BMS_BIBERON_ENTRAR.T2_consumo + SISTEMA_BMS_BIBERON_ENTRAR.t3_consumo + SISTEMA_BMS_BIBERON_ENTRAR.t4_consumo) consumo_TOTAL,
SISTEMA_BMS_BIBERON_ENTRAR.SOC SOC_ENTRADA,
SISTEMA_BMS_BIBERON_SALIR.SOC SOC_SALIDA,
SISTEMA_BMS_BIBERON_SALIR.SOC  - SISTEMA_BMS_BIBERON_ENTRAR.SOC DIF_SOC,
-- Operaciones del vehiculo entre carga y carga
(Select count(1) 
FROM SISTEMA_BMS_ORDENES 
WHERE 
SISTEMA_BMS_BIBERON_ENTRAR.VEHICULO = SISTEMA_BMS_ORDENES.VEHICULO
AND SISTEMA_BMS_ORDENES.FECHA > SISTEMA_BMS_BIBERON_SALIR.FECHA
AND SISTEMA_BMS_ORDENES.FECHA < SISTEMA_BMS_BIBERON_ENTRAR.FECHA) N_Ordenes

from SISTEMA_BMS_BIBERON_ENTRAR
-- Buscamos el movimiento cuando salio de cargar la última vez
left join
	SISTEMA_BMS_BIBERON_SALIR
On SISTEMA_BMS_BIBERON_ENTRAR.VEHICULO = SISTEMA_BMS_BIBERON_SALIR.VEHICULO
And SISTEMA_BMS_BIBERON_SALIR.FECHA < SISTEMA_BMS_BIBERON_ENTRAR.FECHA
And SISTEMA_BMS_BIBERON_SALIR.FECHA = (Select max(FECHA) 
						FROM SISTEMA_BMS_BIBERON_SALIR salir_AUX2 
						WHERE 
						salir_AUX2.VEHICULO = SISTEMA_BMS_BIBERON_SALIR.VEHICULO
						And salir_AUX2.FECHA < SISTEMA_BMS_BIBERON_ENTRAR.FECHA)
WHERE SISTEMA_BMS_BIBERON_ENTRAR.FECHA >='2017/01/10'
-- Solo queremos regsitros donde exista consumo de batería
and (SISTEMA_BMS_BIBERON_SALIR.SOC  - SISTEMA_BMS_BIBERON_ENTRAR.SOC ) >0;