Select
SISTEMA_BMS_BIBERON_ENTRAR.VEHICULO,
SISTEMA_BMS_BIBERON_SALIR.VEHICULO,
SISTEMA_BMS_BIBERON_ENTRAR.FECHA FECHA_ENTRADA,
SISTEMA_BMS_BIBERON_SALIR.FECHA FECHA_SALIDA,
DATEDIFF ( MINUTE , SISTEMA_BMS_BIBERON_ENTRAR.FECHA , SISTEMA_BMS_BIBERON_SALIR.FECHA ) MINUTOS,
SISTEMA_BMS_BIBERON_ENTRAR.SOC SOC_ENTRADA,
SISTEMA_BMS_BIBERON_SALIR.SOC SOC_SALIDA,
SISTEMA_BMS_BIBERON_SALIR.SOC  - SISTEMA_BMS_BIBERON_ENTRAR.SOC DIF_SOC

from SISTEMA_BMS_BIBERON_ENTRAR
-- Buscamos siguiente movimiento de la salida
left join
	SISTEMA_BMS_BIBERON_SALIR
On SISTEMA_BMS_BIBERON_ENTRAR.VEHICULO = SISTEMA_BMS_BIBERON_SALIR.VEHICULO
And SISTEMA_BMS_BIBERON_SALIR.FECHA > SISTEMA_BMS_BIBERON_ENTRAR.FECHA
And SISTEMA_BMS_BIBERON_SALIR.FECHA = (Select min(FECHA) 
						FROM SISTEMA_BMS_BIBERON_SALIR salir_AUX2 
						WHERE 
						salir_AUX2.VEHICULO = SISTEMA_BMS_BIBERON_SALIR.VEHICULO
						And salir_AUX2.FECHA > SISTEMA_BMS_BIBERON_ENTRAR.FECHA)
WHERE 
SISTEMA_BMS_BIBERON_ENTRAR.FECHA >='2017/01/10'
-- Eliminamos cargas fallidas
AND (SISTEMA_BMS_BIBERON_SALIR.SOC  - SISTEMA_BMS_BIBERON_ENTRAR.SOC) > 0
-- Eliminamos cargas de más de 10 horas;
AND DATEDIFF ( MINUTE , SISTEMA_BMS_BIBERON_ENTRAR.FECHA , SISTEMA_BMS_BIBERON_SALIR.FECHA ) < 600;